version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: shopifygenie_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: shopify
      POSTGRES_PASSWORD: shopify_pass
      POSTGRES_DB: shopifygenie
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shopify"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: shopifygenie_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
